'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property id As Integer
    Public Property email As String
    Public Property senha As String
    Public Property cpf As String
    Public Property nome As String
    Public Property idade As Integer
    Public Property profissao As String

End Class
